language: php

php:
  - 7.1
  - 7.2

# PhanTest (tests/files) is the slowest test (~20 seconds).
# Group the remaining tests into groups.
env:
  - TEST_SUITES="PhanTest UtilTest RasmusTest LanguageTest"
  - TEST_SUITES="__FakeSelfTest __FakeRewritingTest __FakePluginTest __FakeFallbackTest"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --prefer-dist install

# TEST_SUITES contains 1 or more space-separated value for TEST_SUITE
# We have a fake TEST_SUITE which runs phan, and check if the exit code is non-zero and the standard output is non-empty.
# This is used instead of a unit test because Phan currently caches too much state for this to be run with other unit tests, and the configuration might end up different within a unit test.
# This was moved into a separate script to stop cluttering up .travis.yml
script:
  - for TEST_SUITE in $TEST_SUITES; do echo "Running $TEST_SUITE"; tests/run_test "$TEST_SUITE" || exit $?; done
  - php package.php
