language: php

php:
  - 7
  - 7.1

env:
  - TEST_SUITE="AnalyzerTest"
  - TEST_SUITE="PhanTest"
  - TEST_SUITE="RasmusTest"
  - TEST_SUITE="LanguageTest"
  - TEST_SUITE="OutputPrinterTest"

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: "7.1"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --prefer-source install

script:
  - ./vendor/bin/phpunit --colors --testsuite "$TEST_SUITE"
  - php package.php

before_deploy:
  - php package.php

deploy:
  provider: releases
  file: build/phan.phar
  skip_cleanup: true
  on:
    tags: true
